### ISSUE TITLE
Cucumber performance reports exception causes the entire build to fail

### ISSUE THREAD

**Issue by jchristi** [TrueDub/cucumber-performance#8]
A null pointer exception during cucumber performance causes the entire build to fail: 
```
WARNING: Publisher com.castlemon.jenkins.performance.CucumberPerfRecorder aborted due to exception
java.lang.NullPointerException
	at com.castlemon.jenkins.performance.reporting.PerformanceReporter.processStep(PerformanceReporter.java:248)
	at com.castlemon.jenkins.performance.reporting.PerformanceReporter.processScenario(PerformanceReporter.java:170)
	at com.castlemon.jenkins.performance.reporting.PerformanceReporter.processFeature(PerformanceReporter.java:117)
	at com.castlemon.jenkins.performance.reporting.PerformanceReporter.processRun(PerformanceReporter.java:83)
	at com.castlemon.jenkins.performance.reporting.PerformanceReporter.getPerformanceData(PerformanceReporter.java:42)
	at com.castlemon.jenkins.performance.reporting.ReportBuilder.generateProjectReports(ReportBuilder.java:21)
	at com.castlemon.jenkins.performance.CucumberPerfRecorder.generateProjectReport(CucumberPerfRecorder.java:104)
	at com.castlemon.jenkins.performance.CucumberPerfRecorder.perform(CucumberPerfRecorder.java:76)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1765)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

It would also be nice to know why the NPE occurred in the first place...

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
